<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Sistema Gerenciador de Ocorrências - SGO';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink()
                ->prependStylesheet($this->basePath() . '/css/signin.css')
                ->prependStylesheet($this->basePath() . '/css/starter-template.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ;
        ?>
    </head>

    <body>
        <div class="container">
            <!--
            <div class="starter-template">
                <h1 class="active"><?php echo $NAME_APPLICATION; ?></h1>
            </div>
            -->

            <!-- <div class="row marketing"> -->
            <?php echo $this->content; ?>
            <!-- </div> -->

            <div class="footer" style="margin-top: 100px;text-align: center">
                <p class="muted credit pull-center">SGO :: Sistema Gerenciador de Ocorrências - Desenvolvido por <a href="">Blue Ray</a>.</p>
            </div>

        </div>

        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;

        echo $this->inlineScript();
        ?>
    </body>
</html>