<div class="row">

    <div class="col-lg-12">

        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="panel-title">
                    <i class="fa fa-chevron-circle-down"></i> Deseja realmente deletar os dados abaixo ?             
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('ocorrencia', array('action' => 'adicionar')); ?>">
                    <input type="hidden" autofocus=""></hidden>
                    <div class="panel-body">
                        <div class="form-group ">
                            <label for="inputEndereco" class="col-lg-3 col-md-3 control-label">Endereço:</label>
                            <div class="col-lg-6 col-md-6">
                                <div class="form-control" >
                                    <?php echo $this->ocorrencia->getId_end(); ?>
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="selectViatura" class="col-lg-3 col-md-3 control-label">Viatura:</label>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-control">
                                    <?php echo $this->ocorrencia->getVtr()->getPrefixo(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="selectArea" class="col-lg-3 col-md-3 control-label">Área:</label>
                            <div class="col-lg-4 col-md-4">
                                <div class="form-control">
                                    <?php echo $this->ocorrencia->getArea()->getDescricao(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="selectPolicial" class="col-lg-3 col-md-3 control-label">Policiais:</label>
                            <div class="col-lg-6 col-md-6">
                                <?php
                                $ids = array();
                                foreach ($this->pols as $p) {
                                    $ids[] = $p->getId_policial();
                                }
                                echo $this->util()->comboPolicial($ids, "disabled");
                                ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputData" class="col-lg-3 col-md-3 control-label">Data:</label>
                            <div class="col-lg-2 col-md-2">
                                <div class="form-control">
                                    <?php echo $this->ocorrencia->getData(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputHora" class="col-lg-3 col-md-3 control-label">Horário:</label>
                            <div class="col-lg-2 col-md-2">
                                <div class="form-control">
                                    <?php echo $this->ocorrencia->getHorario(); ?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputNarracao" class="col-lg-3 col-md-3 control-label">Narração:</label>
                            <div class="col-lg-6 col-md-6">
                                <textarea readonly name="narracao" class="form-control" id="inputNarracao" rows="5" ><?php echo $this->ocorrencia->getNarracao(); ?> </textarea>
                            </div>
                        </div>
                    </div>  
                </form>
            </div>
            <div class="panel-footer">
                <a style="width: 100px" href="<?php echo $this->url('ocorrencia', array('action' => 'deletar', 'id' => $this->ocorrencia->getId_ocorrencia(), 'confirm' => 1)); ?>" class="btn btn-success btn-lg">Sim</a>
                <a style="width: 100px" href="<?php echo $this->url('ocorrencia'); ?>" class="btn btn-danger btn-lg">Não</a>
            </div>
        </div>

    </div>

</div>