<div class="row">

    <div class="col-lg-12">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                   <i class="fa fa-user"></i> Editar Policial ID <?php echo $this->policial->getId_policial(); ?>           
                </div>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('policiais', array('action' => 'editar')); ?>">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="inputNumeral" class="col-lg-3 col-md-3 control-label">Numeral:</label>
                        <div class="col-lg-2 col-md-2">
                            <input type="text" name="numeral" class="form-control" id="inputNumeral" value="<?php echo $this->policial->getNumeral(); ?>" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                        <div class="col-lg-6 col-md-6">
                            <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo" value="<?php echo $this->policial->getNome(); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputNomeGuerra" class="col-lg-3 col-md-3 control-label">Nome de Guerra:</label>
                        <div class="col-lg-6 col-md-6">
                            <input type="text" name="nome_guerra" class="form-control" id="inputNomeGuerra" value="<?php echo $this->policial->getNome_guerra(); ?>" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputMatricula" class="col-lg-3 col-md-3 control-label">Matrícula:</label>
                        <div class="col-lg-2 col-md-2">
                            <input type="text" name="matricula" class="form-control" id="inputMatricula" value="<?php echo $this->policial->getMatricula(); ?>">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="selectGraduacao" class="col-lg-3 col-md-3 control-label">Graduação:</label>
                        <div class="col-lg-2 col-md-2">
                            <?php echo $this->util()->comboGraduacao($this->policial->getGraduacao()->getId_graduacao()); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputDataNasc" class="col-lg-3 col-md-3 control-label">Data de Nascimento:</label>
                        <div class="col-lg-2 col-md-2">
                            <input type="text" name="data_nasc" class="form-control" id="inputDataNasc" maxlength="10"  value="<?php echo $this->util()->toDateDMY($policial->getData_nasc()); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="radioSexo" class="col-lg-3 col-md-3 control-label">Sexo:</label>
                        <div class="col-lg-9  col-md-9">
                            <label class="radio-inline">
                                <input type="radio" name="sexo" id="radioSexo1" value="F" <?php echo $this->policial->getSexo() == 'F'? "checked":""; ?>> Feminino
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="sexo" id="radioSexo2" value="M" <?php echo $this->policial->getSexo() == 'M'? "checked":""; ?>> Masculino
                            </label>
                        </div>
                    </div>
                   
                </div>
                <div class="panel-footer">
                    <input type="hidden" name="id" value="<?php echo $this->policial->getId_policial(); ?>">
                    <button type="submit" class="btn btn-primary">Atualizar Policial</button>
                    <a href="<?php echo $this->url('policiais'); ?>" class="btn btn-default">Voltar</a>
                </div>
            </form>
        </div>

    </div>

</div>