<div class="row">

    <div class="col-lg-12">

        <h1>Policiais <small>Controle dos Policiais</small></h1>
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
        </ol>

    </div>
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="topo-table">
            <a href="<?php echo $this->url('policiais', array('action' => 'adicionar')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

            <div class="btn-group" title="Quantidades por Página">
                <button type="button" class="btn btn-default">005</button>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
                    <li class="active"><a href="#">005</a></li>
                    <li><a href="#">010</a></li>
                    <li><a href="#">025</a></li>
                    <li><a href="#">050</a></li>
                    <li><a href="#">100</a></li>
                </ul>
            </div>

            <form class="form-inline pull-right" role="form">
                <div class="form-group">
                    <label class="sr-only" for="localizar">Buscar...</label>
                    <input type="search" class="form-control" id="localizar" placeholder="Buscar...">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
        </div>

        <br />

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-user"></i> Policiais</h3>
            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th class="header headerSortDown"># <i class="fa fa-sort"></i></th>
                                <th class="header">Numeral <i class="fa fa-sort"></i></th>
                                <th class="header">Nome <i class="fa fa-sort"></i></th>
                                <th class="header">Nome de Guerra <i class="fa fa-sort"></i></th>
                                <th class="header">Matrícula <i class="fa fa-sort"></i></th>
                                <th class="header">Graduação <i class="fa fa-sort"></i></th>
                                <th class="header" style="width: 12%;">Nascimento <i class="fa fa-sort"></i></th>
                                <th class="header" style="width: 7%;">Sexo <i class="fa fa-sort"></i></th>
                                <th class="header" style="width: 10%;text-align: center">Ação <i class="fa "></i></th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php 
                            
                                foreach ($this->policiais as $i=>$policial): ?>
                                <tr>
                                    <td><?php echo ++$i; ?></td>
                                    <td><?php echo $policial->numeral; ?></td>
                                    <td><?php echo $policial->nome; ?></td>
                                    <td><?php echo $policial->nome_guerra; ?></td>
                                    <td><?php echo $policial->matricula; ?></td>
                                    <td><?php echo $policial->id_graduacao; ?></td>
                                    <td><?php echo $policial->data_nasc; ?></td>
                                    <td class="text-center"><?php echo $policial->sexo; ?></td>
                                    <td>
                                        <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('policiais', array('action' => 'detalhes', 'id' => $i)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                        <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('policiais', array("action" => "editar", "id" => $i,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                                        <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('policiais', array("action" => "deletar", "id" => $i,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                    <ul class="pagination pull-right">
                        <li><a href="#">Anterior</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">Próximo</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

