<div class="row">

    <div class="col-lg-12">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    Editar Contato ID <?php echo $this->id; ?>        
                </div>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('vitimas', array('action' => 'editar')); ?>">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                        <div class="col-lg-9 col-md-9">
                            <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo" value="<?php echo $this->form['nome']; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone:</label>
                        <div class="col-lg-9  col-md-9">
                            <input type="text" name="telefone" class="form-control" id="inputTelefonePrincipal" placeholder="Digite seu telefone" value="<?php echo $this->form['telefone']; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputDataNascimento" class="col-lg-3 col-md-3 control-label">Data de Nascimento:</label>
                        <div class="col-lg-9  col-md-9">
                            <input type="text" name="data_nascimento" class="form-control" id="inputTelefoneSecundario" placeholder="Digite a data de nascimento" value="<?php echo $this->form['data_nascimento']; ?>">
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>">
                    <button type="submit" class="btn btn-primary">Atualizar Contato</button>
                    <a href="<?php echo $this->url('vitimas'); ?>" class="btn btn-default">Voltar</a>
                </div>
            </form>
        </div>  

    </div>

</div>